### ISSUE TITLE
k-means clustering

### ISSUE THREAD

**Issue by rebeelouise** [tidymodels/tidymodels.org#21]
Hi!

I have been looking at this tutorial: https://www.tidymodels.org/learn/statistics/k-means/

Is there any information how we can turn our data matrices into the same format?

I found this solution:

```
tagCoordinates<-function(df){
  idx <- which(df>0, arr.ind=T)
  idx<-as.data.frame(idx)
  for (gg in 1:nrow(idx)){
    myRefRow<-idx[gg,1]
    myRefCol<-idx[gg,2]
    idx[['myNo']][gg]<-as.numeric(df[myRefRow,myRefCol])
  }    
  idx <- idx[order(idx[['row']],decreasing=F),]
  rownames(idx)<-NULL
  return(idx)
}
```

However this doesn't really work...

I have a data matrix where columns = samples, and row = pathway expression (numeric). 

What would I do to solve this issue, just so I can follow the tutorial with my own data? :)

**Comment by EmilHvitfeldt** [comment]
Hello @rebeelouise 👋  Please correct me if I'm not understanding correctly, but if your data has the following format as I describe below, then you can use `t()` to transpose the matrix and `tibble::as_tibble()` to turn the matrix into a tibble

``` r
my_data <- matrix(1:15, nrow = 5)
colnames(my_data) <- c("sample1", "sample2", "sample3")
rownames(my_data) <- c("p1", "p2", "p3", "p4", "p5")
my_data
#>    sample1 sample2 sample3
#> p1       1       6      11
#> p2       2       7      12
#> p3       3       8      13
#> p4       4       9      14
#> p5       5      10      15

tibble::as_tibble(t(my_data))
#> # A tibble: 3 × 5
#>      p1    p2    p3    p4    p5
#>   <int> <int> <int> <int> <int>
#> 1     1     2     3     4     5
#> 2     6     7     8     9    10
#> 3    11    12    13    14    15
```

**Comment by EmilHvitfeldt** [comment]
if you have any further questions. let us know!
