### ISSUE TITLE
spelling of bootstraping as a category.

### ISSUE THREAD

**Issue by libjohn** [tidymodels/tidymodels.org#29]
From the site: [tidymodels > Learn page](https://www.tidymodels.org/learn/#category=bootstraping), there is a right-hand sidebar of tidymodels categories  helping further explain how tidymodels can be used.  I think the category 'boostraping" may be misspelled.  I believe it should be 'bootstrapping'.  I was not able to find where the github repo section for a PR.

**Comment by EmilHvitfeldt** [comment]
Thank you for reporting! Should be fixed in #30
