### ISSUE TITLE
Filtering of parsnip model table by package does not work

### ISSUE THREAD

**Issue by hfrick** [tidymodels/tidymodels.org#32]
This is the result of clicking on one of the packages in the drop-down menu for package:

<img width="880" alt="Screenshot 2023-07-16 at 12 18 52" src="https://github.com/tidymodels/tidymodels.org/assets/12950918/9cf62c67-ac6a-4a9f-97fd-34dcd769022a">

**Comment by hfrick** [comment]
It does work for the recipes and broom table :)

**Comment by EmilHvitfeldt** [comment]
No bugs, but misleading. {censored} does not provide any models. What this table shows is which package called `set_new_model()` for each model type, in this case {censored} doesn't https://github.com/search?q=repo:tidymodels/censored%20set_new_model&type=code.

I agree it looks weird, but we could think of another way to talk about "package" origin in the contest of this table

**Comment by EmilHvitfeldt** [comment]
No bugs, but misleading. {censored} does not provide any models. What this table shows is which package called `set_new_model()` for each model type, in this case {censored} doesn't https://github.com/search?q=repo:tidymodels/censored%20set_new_model&type=code.

I agree it looks weird, but we could think of another way to talk about "package" origin in the contest of this table

**Comment by hfrick** [comment]
Ah, I see! So this table was created when we still had model definitions in extension packages, makes sense. I think the content of this column should probably change to reflect where the engines are, rather than the model definition.
