### ISSUE TITLE
About `parsnip::set_model_arg`

### ISSUE THREAD

**Issue by thierrymoudiki** [tidymodels/tidymodels.org#33]
Hi, 

Trying to implement a custom model on a fork, and I'm referring to the following line of code (about `parsnip::set_model_arg`'s arguments `parsnip` and `original`): 

https://github.com/tidymodels/tidymodels.org/blob/31d45ffdcd4a0f01d921737e2f6993617fa3708b/learn/develop/models/index.qmd#L118

Is there any reason why this would be a single character? Is there any way to specify more than one hyperparameter? I'm probably missing something here. 

Thanks.

**Comment by hfrick** [comment]
The way to specify how more than one hyperparameter is translated between parsnip and the engine is to use several calls to `set_model_arg()` which is used to specify just one at a time. Not sure ad-hoc why that isn't vectorized but I'm guessing it might be because of the many checks run on all the inputs. It's a good question though!

As an example, here are two of the five main arguments for `boost_tree()` specified for the `mboost` engine in the censored package:

https://github.com/tidymodels/censored/blob/f9eccb68a51159d55390ac592605600e5d659ef3/R/boost_tree-data.R#L27-L43

**Comment by thierrymoudiki** [comment]
Great, thanks @hfrick ! If there's no direct correspondance with a `parsnip` hyperparameter, can I just specify `parsnip = ""` in `parsnip::set_model_arg`?

**Comment by hfrick** [comment]
`set_model_arg()` is specifically for the translation of main arguments of the parsnip model function. In the above example, `boost_tree()` is what I call the parsnip model function and the main arguments are the ones listed [in this section](https://parsnip.tidymodels.org/reference/boost_tree.html#arguments) (apart from `mode` and `engine`, of course). 

Parameters to the engine that don't match up to any of those main arguments are _not_ specified via `set_model_arg()`. Those are specified by the user in `set_engine()` - as opposed to you, the developer. As a pseudo example, the user would specify some `engine_specific_arg` like this:

```
boost_tree() %>%
  set_engine("the_engine_you_want", engine_specific_arg = some_value)
```

**Comment by thierrymoudiki** [comment]
This second option is **extremely** tricky. I've been trying to export [my package](https://techtonique.r-universe.dev/bcn#) function, `bcn::bcn`, to the package's (parsnip) interface (not sure if mentioning @export in roxgen2 is enough), without much success. That's why I tried `parsnip::set_model_arg` and the `.qmd` file in the first place. 

Here's what I tried (only the code matters, the text remains mostly unchanged): 
https://github.com/thierrymoudiki/tidymodels.org/blob/main/learn/develop/models/index.qmd

**Comment by thierrymoudiki** [comment]
@hfrick @EmilHvitfeldt Any chance? No chance? :)

**Comment by hfrick** [comment]
Could you be specific about where you run into problems and what your question is? That makes it a lot easier to help you.

**Comment by thierrymoudiki** [comment]
Never mind. Everything's already been said in the previous messages. `mlr3` is much more accessible. Thanks for your help!
