### ISSUE TITLE
Performance: Specify which level is used in AUC

### ISSUE THREAD

**Issue by jxu** [tidymodels/tidymodels.org#42]
https://www.tidymodels.org/start/resampling/#performance
It's not clear for which class level `predict(rf_fit, cell_train, type = "prob"))` will return a probability for. Seems to be the first level.  
It's also nontrivial to lookup the function docs because you need `?predict.model_fit` and not generic `?predict`. 
The `roc_auc` and `roc_curve` code can change this using `event_level`, but that is only in the docs for that function. I'm not sure if I can change it for `metrics()` (to be fair, that function isn't used on the page).

**Comment by EmilHvitfeldt** [comment]
> It's not clear for which class level predict(rf_fit, cell_train, type = "prob")) will return a probability for. Seems to be the first level.

It returns the probability of all the class levels

``` r
library(tidymodels)
library(modeldata)

data(cells, package = "modeldata")

set.seed(123)
cell_split <- initial_split(cells %>% select(-case), 
                            strata = class)

cell_train <- training(cell_split)
cell_test  <- testing(cell_split)

rf_mod <- 
  rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

set.seed(234)

rf_fit <- 
  rf_mod %>% 
  fit(class ~ ., data = cell_train)

predict(rf_fit, cell_train, type = "prob")
#> # A tibble: 1,514 × 2
#>    .pred_PS .pred_WS
#>       <dbl>    <dbl>
#>  1    0.739   0.261 
#>  2    0.934   0.0659
#>  3    0.929   0.0713
#>  4    0.961   0.0391
#>  5    0.922   0.0781
#>  6    0.711   0.289 
#>  7    0.989   0.0112
#>  8    0.802   0.198 
#>  9    0.853   0.147 
#> 10    0.741   0.259 
#> # ℹ 1,504 more rows
```

> It's also nontrivial to lookup the function docs because you need ?predict.model_fit and not generic ?predict.

yes that is a known issue, that is hard for us to deal with as it is integral to how S3 methods work.

> The `roc_auc()` and `roc_curve()` code can change this using event_level, but that is only in the docs for that function. I'm not sure if I can change it for `metrics()` (to be fair, that function isn't used on the page).

It isn't unreasonable to expect `metrics()` to take `event_level`. you also can't modify the `sum` argument for the `mn_log_loss()` metric. For now I don't think it is worth the trouble to modify `metrics()` since you can use `metric_set()` to create your own metrics function that does what you need.

**Comment by jxu** [comment]
You're right about predict. I got confused between probability and predicted class. 
The important part is the getting started article should mention why .pred_PS column was chosen for roc_auc as positive and how you could treat the other level as positive.
