### ISSUE TITLE
Problem in "Accounting for Censoring in Performance Metrics for Event Time Data"

### ISSUE THREAD

**Issue by errants** [tidymodels/tidymodels.org#49]
Hi.

In this article, you have written how to fit a bagged survival tree model, then use augment() function to return a dataset that augmented with predictions. However, I run the code you posted online, it returns an error 
"Error in `augment()`:
! Unknown mode: censored regression
---
Backtrace:
    ▆
 1. ├─generics::augment(bag_tree_fit, sim_val, eval_time = time_points)
 2. └─parsnip:::augment.model_fit(bag_tree_fit, sim_val, eval_time = time_points)"

I don't know how to do with it, can you give me some advice?

The code I have problem with:

"bag_tree_fit <- 
  bag_tree() %>% 
  set_mode("censored regression") %>% 
  set_engine("rpart") %>% 
  fit(event_time ~ ., data = sim_tr)

val_pred <- augment(bag_tree_fit, sim_val, eval_time = time_points)"

Thank you.
Shao

**Comment by hfrick** [comment]
Hi! This looks like you might not have the development versions installed. For this particular article, you need to install the development versions of parsnip and censored. You can do so for example via the pak package:

```
#install.packages("pak")

pak::pak(c("tidymodels/censored", "tidymodels/parsnip"))
```

Does this solve your problem?

**Comment by errants** [comment]
Yes! I solved problem by updating parsnip to 1.1.1, originally my version was 1.1.0. Thank you very much. I’ll check the change log of the package first. Thank you again, have a nice day.

---- Replied Message ----
| From | Hannah ***@***.***> |
| Date | 11/17/2023 17:36 |
| To | ***@***.***> |
| Cc | errants ***@***.***>,
Author ***@***.***> |
| Subject | Re: [tidymodels/tidymodels.org] Problem in "Accounting for Censoring in Performance Metrics for Event Time Data" (Issue #49) |

Hi! This looks like you might not have the development versions installed. For this particular article, you need to install the development versions of parsnip and censored. You can do so for example via the pak package:

#install.packages("pak")

pak::pak(c("tidymodels/censored", "tidymodels/parsnip"))


Does this solve your problem?

**Comment by hfrick** [comment]
I'm gonna go ahead and close this. Let us know if you run into further problems!

**Comment by errants** [comment]
Ok, sorry, I don’t realized I have to close it on GitHub

---- Replied Message ----
| From | Hannah ***@***.***> |
| Date | 11/28/2023 18:40 |
| To | ***@***.***> |
| Cc | errants ***@***.***>,
Author ***@***.***> |
| Subject | Re: [tidymodels/tidymodels.org] Problem in "Accounting for Censoring in Performance Metrics for Event Time Data" (Issue #49) |

Closed #49 as completed.

**Comment by hfrick** [comment]
No worries! You don't have to :)

**Comment by errants** [comment]
🫰

---- Replied Message ----
| From | Hannah ***@***.***> |
| Date | 11/28/2023 19:28 |
| To | ***@***.***> |
| Cc | errants ***@***.***>,
Author ***@***.***> |
| Subject | Re: [tidymodels/tidymodels.org] Problem in "Accounting for Censoring in Performance Metrics for Event Time Data" (Issue #49) |

No worries! You don't have to :)
