### ISSUE TITLE
broken contribute link

### ISSUE THREAD

**Issue by dss2q** [tidymodels/tidymodels.org#73]
## The problem

On the contribute page ([https://www.tidymodels.org/contribute/](https://www.tidymodels.org/contribute/)), there is a broken link in the final paragraph (emphasis added):

> The tidymodels packages are explicitly built to support the creation of other modeling packages, and we would love to hear about what you build yourself! Check out our learning resources for [**developing custom modeling tools**](https://www.tidymodels.org/learn/develop/).

That page was functional in the past based on a look via the [WayBack Machine (2023-06-02)](https://web.archive.org/web/20230602134019/https://www.tidymodels.org/learn/develop/). Submitting as a bug report to "file the issue", as per the message on the not found page.

**Comment by EmilHvitfeldt** [comment]
Hello @dss2q 👋 

Thanks for catching the bug, it has been fixed now
