### ISSUE TITLE
Documentation mentions deprecated metric_vec_template() ?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidymodels/tidymodels.org#77]
It seems that the documentation for "Custom performance metrics" in https://www.tidymodels.org/learn/develop/metrics/ mentions a function `metric_vec_template()` that is deprecated as well as not used in the documentation itself?

> 2. Pass on that implementation function to metric_vec_template().

so the page might need a quick refresh?

Thanks!

**Comment by EmilHvitfeldt** [comment]
Thank you for noticing that! should be fixed now
